apiVersion: v1
kind: Service
metadata:
  name: search-nearby-places-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: search-nearby-places
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
